package com.vk.ddbtest.models

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

// https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.html
@DynamoDBTable(tableName = "ProductInfo")
// Exception in thread "main" com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: could not instantiate class com.vk.ddbtest.models.ProductInfo
//Exception in thread "main" com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: could not invoke null on class com.vk.ddbtest.models.ProductInfo with value test-123 of type class java.lang.String
data class ProductInfo (
        @DynamoDBHashKey(attributeName = "Id")
        @DynamoDBAutoGeneratedKey
        var id: String?=null,

        @DynamoDBAttribute(attributeName ="MSRP")
        var msrp: String?=null,

        @DynamoDBAttribute(attributeName ="Cost")
        var cost: Int?=0
)