/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.vk.kafkakotlin

import com.vk.kafkakotlin.producers.SimpleProducer


fun main(args: Array<String>) {
    SimpleProducer("localhost:9092").produce()
}
