---
AWSTemplateFormatVersion: '2010-09-09'
Description: Last time we used CLI, this time we use CF
Resources:
  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Properties:
      RoleName: "lambda-with-cf-role"
      Path: "/"
      AssumeRolePolicyDocument:
        # https://github.com/PacktPublishing/Serverless-Programming-Cookbook/blob/master/Chapter01/your-first-lambda-with-cloud-formation/resources/lambda-with-pojos-cf-template.yml
        # https://gist.github.com/magnetikonline/c314952045eee8e8375b82bc7ec68e88
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html
        - PolicyName: 'lambda-with-cf-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
  LambdaFunctionWithCF:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: 'vk-serverless-20200201'
        S3Key: greeter-1.0.0.jar
      FunctionName: first-lambda-with-cloud-formation
      Handler: com.vk.serverless.MyLambdaHandler::handleRequest
      MemorySize: 512
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
      Role:
        # To get the role Arn, we used the GetAtt function passing the logical name of the Role and the property name Arn:
        # Fn::GetAtt is an intrinsic function that returns the value of an attribute from a resource in the template. 
        # https://stackoverflow.com/questions/58617503/cloudformation-when-to-use-getatt-ref-vs
        Fn::GetAtt:
        - IamRoleLambdaExecution
        - Arn
      Runtime: java8
      Timeout: 15
    DependsOn:
      - IamRoleLambdaExecution