/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.vk.kafkakotlin

import com.vk.kafkakotlin.consumers.SimpleConsumer

fun main(args: Array<String>) {
    SimpleConsumer("localhost:9092").process()
}
